Initialize repo
cg-tuwien/VulkanLaunchpadStarter pull request #2
Opened 2023-01-13 13:46 UTC by electrocnic

2023-01-13 16:05 UTC, johannesugb requested changes
What are the contents of the `/test` directory? 
These tests are not run automatically, are they? 
Are they of any use to users or just for our internal testing? If it is the latter, can we somehow hide them from users?

2023-01-13 16:05 UTC, johannesugb commented on src/Main.cpp
> +	float aspect_ratio = window_width / window_height;
```suggestion
	const float field_of_view = 60.0f;
	const float near_plane_distance = 0.1f;
	const float far_plane_distance = 100.0f;
	const float aspect_ratio = window_width / window_height;
```

2023-01-15 13:07 UTC, fknfilewalker commented on src/Main.cpp
> +	float aspect_ratio = window_width / window_height;
why not constexpr?

2023-01-15 13:09 UTC, fknfilewalker commented
> What are the contents of the `/test` directory? These tests are not run automatically, are they? Are they of any use to users or just for our internal testing? If it is the latter, can we somehow hide them from users?

They are not really tests. 
I am not really sure why we need them but if I remember correctly they are docker configs which we can use if someone on linux has problems with installing deps.

2023-01-15 13:26 UTC, johannesugb commented on src/Main.cpp
> +	float aspect_ratio = window_width / window_height;
Yeah, that's even better. Updated!

2023-01-15 13:27 UTC, johannesugb commented
> I am not really sure why we need them but if I remember correctly they are docker configs which we can use if someone on linux has problems with installing deps.

Hmm so that means we should keep them?

2023-01-15 13:37 UTC, fknfilewalker commented
> > I am not really sure why we need them but if I remember correctly they are docker configs which we can use if someone on linux has problems with installing deps.
> 
> Hmm so that means we should keep them?

I don't know, we could just copy the commands to install the deps in the readme, but in general people who are using linux normally know how to use linux so I wouldn't care too much about them, but let's see what @electrocnic thinks.

2023-01-17 10:13 UTC, johannesugb commented
> > > I am not really sure why we need them but if I remember correctly they are docker configs which we can use if someone on linux has problems with installing deps.
> > 
> > 
> > Hmm so that means we should keep them?
> 
> I don't know, we could just copy the commands to install the deps in the readme, but in general people who are using linux normally know how to use linux so I wouldn't care too much about them, but let's see what @electrocnic thinks.

So.. @electrocnic what do you think?

2023-01-17 11:57 UTC, merged

2023-01-17 13:22 UTC, electrocnic commented
I will incorporate those lines for each linux distro into the readme, perhaps?

And therefore also add hints for users which distros we officially support and which not.